import Head from 'next/head';
import Navbar from '../components/Navbar';
import HomePage from './homepage';
import Contact from './contact';
import Project from './projects';
import Footer from '../components/Footer';
import Skill from './skills';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sibulele Saba</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href=""/>
      </Head>

      <Navbar />
      <HomePage />
      <Project />
      <Skill />
      <Contact />
      <Footer />
    </div>
  )
}
